### PR TITLE
add missing page numbers 

### PR DESCRIPTION
**Pull request by 11do**
You do not have to write any comment here (but you can).

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
I rebased this branch based on the latest "official" main branch, so that it becomes a streamlined diff. Please do so on your own in future contributions.

**Comment by jvoigtlaender** [comment]
Also, there is still an "editorconfig violation" in your changed file.

You can see that here:

image
as well as here: 
image

and under Details:

https://github.com/fmidue/ProPa-Subtitles/actions/runs/5761803241/job/15620349410?pr=64#step:4:396

**Comment by jvoigtlaender** [comment]
The best way to prevent such problems is to actually heed what the README says:

> Note that the *editor settings* provided as an `.editorconfig` file can be enforced by most editors either [directly](https://editorconfig.org/#pre-installed) or [after installing some plugin](https://editorconfig.org/#download).

**Comment by 11do** [comment]
oki. I will try to solve the problem. Thanks for you help!!!

**Pull request closed without merging**
